name: Build Package

on:
  workflow_dispatch:
    inputs:
      release:
        type: choice
        description: Release type
        options:
          - none
          - pre-release
          - release

env:
  SCCACHE_CACHE_SIZE: 6G
  SCCACHE_DIR: /home/runner/.cache/sccache

jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v3
          with:
            repository: google/bbr
            ref: v3
            path: bbr

        - name: Get current time
          id: time
          run: echo "time=$(date -u "+%Y-%m-%d-%H%M%S")" >> $GITHUB_OUTPUT

        - name: Setup dependencies
          run: |
            sudo apt-get update
            sudo apt-fast install -y build-essential \
              bc kmod cpio flex libncurses5-dev \
              libelf-dev libssl-dev dwarves bison \
              gawk openssl libssl-dev dkms libudev-dev \
              libpci-dev libiberty-dev autoconf \
              rpm debhelper
        
        - name: Install LLVM and Clang
          uses: KyleMayes/install-llvm-action@v1
          with:
            version: "16"
        
        - name: Setup sccache
          uses: mozilla-actions/sccache-action@v0.0.3

        - name: Get .config
          run: curl -sSL https://raw.githubusercontent.com/Zxilly/bbr-v3-deb/master/.config > bbr/.config

        - name: Setup cache
          uses: actions/cache@v3
          with:
            path: /home/runner/.cache/sccache
            key: sccache-${{ hashFiles('bbr/.config') }}-llvm
        
        - name: Build
          working-directory: bbr
          env:
            KBUILD_BUILD_TIMESTAMP: ''
            KDEB_COMPRESS: "xz"
          run: |
            make \
              LLVM=1 \
              LOCALVERSION="" \
              CC="sccache clang" \
              HOSTCC="sccache clang" \
              olddefconfig
            # Build deb
            make \
              LLVM=1 \
              LOCALVERSION="" \
              CC="sccache clang" \
              HOSTCC="sccache clang" \
              -j`nproc` \
              bindeb-pkg
            # reset version
            rm .version
            # Build rpm
            make \
              LLVM=1 \
              LOCALVERSION="" \
              CC="sccache clang" \
              HOSTCC="sccache clang" \
              RPMOPTS="--nodeps" \
              -j`nproc` \
              rpm-pkg
        
        - name: Upload config
          uses: actions/upload-artifact@v3
          with:
            name: config
            path: bbr/.config
        
        - name: Upload deb
          uses: actions/upload-artifact@v3
          with:
            name: deb
            path: linux-*.deb
        
        - name: Upload rpm
          uses: actions/upload-artifact@v3
          with:
            name: rpm
            path: /home/runner/rpmbuild/RPMS/x86_64/*.rpm

        - name: Release
          if: ${{ github.event.inputs.release != 'none' }}
          uses: ncipollo/release-action@v1
          with:
            artifacts: "linux-*.deb,/home/runner/rpmbuild/RPMS/x86_64/*.rpm"
            prerelease: ${{ github.event.inputs.release == 'pre-release' }}
            makeLatest: ${{ github.event.inputs.release == 'release' }}
            tag: ${{ steps.time.outputs.time }}
        
